[workspace]
members = ["tackc", "tackc_lib", "tackc_meta", "fuzz/*"]
resolver = "3"

[workspace.dependencies]
serde = "1.0"
thiserror = "2.0"
dashmap = "6.2"
clap = "4.6"
walkdir = "2.5"
tackc_lib = { version = "0.1.0", path = "tackc_lib" }
tackc_fuzz = { version = "0.0.0", path = "fuzz/shared" }
bumpalo = "3.20"
libfuzzer-sys = "0.4.13"
rustc-hash = "2.1"
sha2 = "0.11.0"
insta = "1.48"
proptest = "1.11"
thin-vec = "0.2.18"
ignore = "0.4.27"
nonzero = "0.2.0"
aho-corasick = "1.1"
colored = "3.1"
tackc_meta = { version = "0.1.0", path = "tackc_meta" }
anyhow = "1.0.104"
serde_json = "1.0.151"
derive_more = "2.1.1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

# Lints to error against to force fixes without allowing #[expect]
missing_assert_message = "forbid"
multiple_unsafe_ops_per_block = "forbid"
allow_attributes = "forbid"
doc_include_without_cfg = "forbid"
precedence_bits = "forbid"
same_name_method = "forbid"
semicolon_inside_block = "forbid"
try_err = "forbid"
unused_result_ok = "forbid"
mixed_read_write_in_expression = "forbid"
mutex_atomic = "forbid"
mutex_integer = "forbid"
pathbuf_init_then_push = "forbid"
pattern_type_mismatch = "forbid"
rc_mutex = "forbid"
return_and_then = "forbid"
unseparated_literal_suffix = "forbid"
shadow_same = "forbid"
str_to_string = "forbid"
string_lit_chars_any = "forbid"
unnecessary_rest_pattern = "forbid"
as_pointer_underscore = "forbid"
as_underscore = "forbid"
clone_on_ref_ptr = "forbid"
if_then_some_else_none = "forbid"
impl_trait_in_params = "forbid"
let_underscore_must_use = "forbid"
map_with_unused_argument_over_ranges = "forbid"

# Lints to error against in order to force fixes while still allowing #[expect].
doc_paragraphs_missing_punctuation = "deny"
indexing_slicing = "deny"
disallowed_types = "deny"
needless_raw_strings = "deny"
non_zero_suggestions = "deny"
rc_buffer = "deny"
redundant_type_annotations = "deny"
string_slice = "deny"
decimal_literal_representation = "deny"
exit = "deny"

# Lints to warn against in order to require CHECKED.
mem_forget = "warn"
cfg_not_test = "warn"

# Lints to warn against that aren't meant to be #[expect]ed.
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"

# Lints to warn against to be pedantic
rest_pat_in_fully_bound_structs = "warn"
lossy_float_literal = "warn"
missing_docs_in_private_items = "warn"

# Lints to allow.
must_use_candidate = "allow"
should_panic_without_expect = "allow"
type_complexity = "allow"

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "forbid"
