//! Turns a flat list of modules into a tree of modules.

use std::borrow::Cow;

use rustc_hash::FxHashSet;
use thin_vec::thin_vec;

use crate::{
    error::Diag,
    file::FileId,
    frontend::ast::{AstModule, Item},
    global::Global,
    sema::{LogicalPath, NonEmptyLogicalPath},
    utils::{
        UnwrapExt,
        hash::IdentityHashMap,
        intern::Interned,
        tree::{TreeItem, TreeItemExt},
    },
};

/// A tree of modules, using [`ModuleNode`].
#[derive(Debug)]
pub struct ModuleTree {
    /// The inner nodes.
    pub nodes: IdentityHashMap<Interned<str>, ModuleNode>,
}

impl ModuleTree {
    /// Displays a representation of this module tree.
    pub fn display(&self, global: &Global) -> String {
        if self.nodes.is_empty() {
            return String::new();
        }

        let mut nodes = self.nodes.values().collect::<Vec<_>>();
        nodes.sort_by_key(|val| val.path.first().display(global));

        nodes.into_iter().fold(String::new(), |val, elem| {
            val + "\n" + &elem.display(global)
        })
    }

    /// Gets a module from the tree, ignoring visibillity.
    pub fn get(&self, path: &LogicalPath) -> Option<&ModuleNode> {
        if path.is_empty() {
            return None;
        }

        let (first, rest) = path.split_at(1);
        let first = first
            .first()
            // `first` represents `&path[0..1]`, which will always have a length of at least one.
            .expect_unreachable(); // CHECKED(Chloe)

        let mut node = self.nodes.get(&first.identifier()?)?;
        let mut nodes = &node.nodes;

        for &next in rest {
            node = nodes.get(&next.identifier()?)?;
            nodes = &node.nodes;
        }

        Some(node)
    }
}

/// A node in a tree of modules.
#[derive(Debug)]
pub struct ModuleNode {
    /// The path of this module.
    pub path: NonEmptyLogicalPath,
    /// The name of this module.
    pub name: Interned<str>,
    /// The files that make up this module.
    pub files: Vec<FileId>,
    /// The items of this module.
    pub items: IdentityHashMap<Interned<str>, Item>,
    /// The children of this module.
    pub nodes: IdentityHashMap<Interned<str>, Self>,
    /// Whether this module is exported or not.
    pub exported: bool,
    /// Whether this module was automatically generated by a child module or not.
    auto: bool,
}

impl ModuleNode {
    /// Gets the name of this module.
    pub const fn get_name(&self) -> Interned<str> {
        self.name
    }

    /// Gets the path of this module, returning it by reference.
    pub const fn path(&self) -> &NonEmptyLogicalPath {
        &self.path
    }

    /// Gets the path of this module, returning it by value.
    pub fn into_path(self) -> NonEmptyLogicalPath {
        self.path
    }
}

impl TreeItem for ModuleNode {
    fn name<'a>(&'a self, global: &'a Global) -> Cow<'a, str> {
        debug_assert!(
            !self.path.is_empty(),
            "ModuleNode paths shouldn't be empty!"
        );

        let path = self.name.get(&global.interner);
        let exp = if self.exported { "exp " } else { "" };

        format!("{exp}{path}").into()
    }

    fn children(&self) -> Cow<'_, [&dyn TreeItem]> {
        self.nodes
            .values()
            .map(|s| s as &dyn TreeItem)
            .collect::<Vec<_>>()
            .into()
    }
}

/// Errors for module analysis.
pub enum ModuleAnalyzerError {
    /// A conflict in visibillities for duplicate modules.
    ModuleVisibillityConflict(LogicalPath, Vec<FileId>),
    /// An item name is repeated in a module.
    DuplicateItem(LogicalPath),
}

impl ModuleAnalyzerError {
    /// Displays the error.
    ///
    /// # Panics
    /// This function panics if the file used to produce this error is not in `global`'s file list.
    pub fn display(&self, global: &Global) -> String {
        match *self {
            Self::ModuleVisibillityConflict(ref path, ref files) => {
                let mut string = format!(
                    "Duplicated module {} with different visibillities! Files: ",
                    path.display(global)
                );

                for file in files {
                    assert!(
                        global.file_list().contains(*file),
                        "Global doesn't contain file!"
                    );

                    let file = global
                        .file_list()
                        .get(*file)
                        // This was asserted above.
                        .expect_unreachable(); // CHECKED(Chloe)

                    string += &file.path().display().to_string();
                    string += ", ";
                }

                // Remove last comma
                string.truncate(string.len() - 2);

                Diag::without_span(string).display(global)
            }
            Self::DuplicateItem(ref path) => {
                Diag::without_span(format!("duplicate item {}!", path.display(global)))
                    .display(global)
            }
        }
    }
}

/// Run the module analyzer on a list of modules.
pub fn analyze(modules: Vec<AstModule>, global: &Global) -> (ModuleTree, Vec<ModuleAnalyzerError>) {
    let mut root = IdentityHashMap::default();
    let mut error_set = FxHashSet::default();
    let mut errors = Vec::new();

    for module in modules {
        let Some(mod_stmt) = module.mod_stmt else {
            continue;
        };
        let Some(path) = mod_stmt.path else {
            continue;
        };
        let exported = mod_stmt.exported;

        // Hacky fix to ensure node is initialized,
        // this value is never actually used.
        let mut default = ModuleNode {
            path: NonEmptyLogicalPath::new(LogicalPath::from(thin_vec![
                global.interner.intern_str("<ERROR>")
            ]))
            // Since the LogicalPath passed is non-empty, Some will be returned.
            .expect_unreachable(), // CHECKED(Chloe)
            name: global.interner.intern_str("<ERROR>"),
            files: vec![],
            items: IdentityHashMap::default(),
            nodes: IdentityHashMap::default(),
            exported: false,
            auto: true,
        };

        let mut nodes = &mut root;
        let mut node = &mut default;
        let mut logical_path = LogicalPath::new();

        for component in &path {
            let Some(component) = component else {
                break;
            };

            let name = component.get(&global.interner).0;

            logical_path.push(name);

            let new_node = nodes.entry(name).or_insert(ModuleNode {
                path: NonEmptyLogicalPath::new(logical_path.clone())
                    // This was pushed to above.
                    .expect_unreachable(), // CHECKED(Chloe)
                name,
                files: vec![],
                items: IdentityHashMap::default(),
                nodes: IdentityHashMap::default(),
                exported: true,
                auto: true,
            });
            node = new_node;
            nodes = &mut node.nodes;

            debug_assert!(
                !node.path.is_empty(),
                "ModuleNode paths shouldn't be empty!"
            );
        }

        if !node.auto {
            for item in module.items.into_iter().flatten() {
                let Some(name) = item.get_name(global) else {
                    continue;
                };
                node.items.insert(name, item);
            }

            if node.exported != exported {
                error_set.insert(logical_path);
                continue;
            }

            continue;
        }

        for item in module.items.into_iter().flatten() {
            let Some(name) = item.get_name(global) else {
                continue;
            };

            if node.items.contains_key(&name) {
                let mut path = logical_path.clone();
                path.push(name);
                errors.push(ModuleAnalyzerError::DuplicateItem(path));
            }

            node.items.insert(name, item);
        }
        node.files.push(module.file);
        node.exported = exported;
        node.auto = false;
    }

    let tree = ModuleTree { nodes: root };

    let errors = error_set
        .into_iter()
        .map(|path| {
            let node = tree
                .get(&path)
                // Paths added to the error_set always exist in the tree.
                .expect_unreachable(); // CHECKED(Chloe)

            ModuleAnalyzerError::ModuleVisibillityConflict(path, node.files.clone())
        })
        .chain(errors)
        .collect();

    (tree, errors)
}
