Item = ConstItem ;

ConstItem = CONST IDENTIFIER ( COLON Expression )? EQ Expression ;

Expression = Comparison ;
Comparison = Term ( ( GT | LT | GT_EQ | LT_EQ | EQ_EQ | BANG_EQ ) Term )?
Term = Factor ( ( PLUS | MINUS ) Factor )* ;
Factor = Unary ( ( STAR | SLASH ) Unary )* ;

Unary = ( MINUS | BANG ) Unary
    | Postfix
    ;
Postfix = Grouping (L_PAREN ArgList? R_PAREN
    | L_BRACKET Expression R_BRACKET
    | DOT IDENTIFIER)* ;
Grouping = L_PAREN Expression R_PAREN
    | Primary ;
Primary = IDENTIFIER
    | INT_LIT
    | FLOAT_LIT
    ;

ArgList = Expression ( COMMA Expression )* COMMA? ;
